### ISSUE TITLE
pishutdown uses 100% of a CPU core

### ISSUE THREAD

**Issue by andrum993** [raspberrypi-ui/pishutdown#19]
Tested on:
- Pi 5 and Pi 4 running Raspberry Pi OS 2024-05-04 Bookworm 64-bit, fully up to date
- Pi 3B+ running Raspberry Pi OS 2024-05-04 Bookworm 32-bit, fully up to date

lxde-pi-shutdown uses a whole CPU core when running. Example:

![20240807_17h22m30s_grim-1](https://github.com/user-attachments/assets/55b25025-0196-4c2f-a104-8e1d43d1bdf3)

Happens on both wayland and X11 desktops.

**Comment by spl237** [comment]
Known issue. Due to the fact that it needs to poll the hardware to intercept presses of the physical power switch, it unavoidably has a high CPU load. That said, said load really isn't a problem, as it will stop as soon as the Pi powers down... ;)
